materia = str(input("digite sua materia:"))
nota1 = float(input("digite sua 1 nota:"))
nota2 = float(input("digite sua 2 nota:"))
nota3 = float(input("digite sua 3 nota:"))
nota4 = float(input("digite sua 4 nota:"))
nota_final = float((nota1 + nota2 + nota3 + nota4) / 4)
print(f"Sua nota média em {materia} é:{nota_final}")